include: '.autodevops-template.yml'
include: '.database-backup.yml'

variables:
  PROJECT_NAME: blockexplorer-production-db
  MAX_MEM: "8Gi"
  MAX_CPU: "4"
  PERSISTENT_VOLUMES: "postgres:/var/lib/postgresql/data:240Gi"
  
  APP_PORT: "5432" # Specify the main communication port to the App. This port will be used to determine if service is online. (default 5000)     
  INGRESS_PORT: "" # Specify the port exposed externally via nginx. Please set it accordingly  to avoid security exposure. (default none) 
  INTERNAL_PORTS: "" # Specify additional ports exposed to the cluster, separated by space. (default none)
  EXTERNAL_PORTS: "5432" # Specify additional ports exposed to the world, separated by space. (default node)
  SKIP_TESTS: "true"
